### ISSUE TITLE
Check existing data when using dat clone

### ISSUE THREAD

**Issue by agattis** [dat-ecosystem-archive/dat#885]
It's much easier to jump into dat if you can import your existing data sets. 

Use case:

Currently using rsync to mirror 20K files totaling 10TB from a single server to a handful of client servers. Data is already in sync. 

Cloning a dat from the central server onto an existing directory will use existing client data where possible and remove inconsistencies.

**Comment by mafintosh** [comment]
Great idea. We should support this I agree

**Comment by TemaSM** [comment]
Any updates? I think we really need it

**Comment by joehand** [comment]
Thanks for pinging this one. Definitely a good idea.

Note to self on implementation from mafintosh:

>  we need a .verifyData method in hypercore that checks that data in it's feed matches the hashes stored

**Comment by damons** [comment]
On implementation, for future, I'm not sure if this is related, but I can't help but dream about ways to optimize these transfers, if there are multiple locations with partial data, there might be some sneaky optimizations possible using the tricks hidden in the [Pedersen Commit Scheme](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjl5dj8q97ZAhXGzIMKHVv9CMIQFghAMAM&url=http%3A%2F%2Fhomepages.cs.ncl.ac.uk%2Fchangyu.dong%2Fpapers%2Fmmm-acns17.pdf&usg=AOvVaw1GBZNPweyjLLLz4X0siDy3), relaxing verification a bit, if one is somewhat confident that the current graph is secure from prying eyes, but I may be terribly off-base.  I haven't looked into protocol incompatibilities at all.  Feel free to ignore.

**Comment by martinheidegger** [comment]
Referencing this here: https://github.com/mafintosh/hyperdrive/issues/203
